<?php

/**
 * @file
 * Uninstall functions for trustarc module.
 */

/**
 * Implements hook_uninstall().
 */
function trustarc_uninstall(): void {
  \Drupal::service('config.factory')
    ->getEditable('trustarc.settings')
    ->delete();
}

/**
 * Initializes Consent Behavior config for existing installs.
 */
function trustarc_update_10201(): string {
  $config = \Drupal::configFactory()->getEditable('trustarc.settings');
  $cmp_consent_config = $config->get('cmp_consent_config');

  if ($cmp_consent_config === NULL || $cmp_consent_config === '') {
    $config->set('cmp_consent_config', 'notice_behavior')->save();
  }

  return 'Initialized TrustArc consent behavior default setting.';
}
